server:
  port: 5000
  ssl:
    key-alias: 202012222_cert
    key-store: classpath:202012222_server.keystore
    key-store-password: Wantdo.123
    key-store-type: JKS
  tomcat:
    use-relative-redirects: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG